# name of the addon
name: "🚇 BetterBahn"
# description of the addon
description: "Find cheaper train tickets 💸 with split-ticketing."
# version of the addon
version: "dev"
# slug of the addon
slug: "betterbahn-srv"
# startup mode
init: false
# supported architectures
arch:
  - aarch64
  - amd64
# ports used by the addon
ports:
  3000/tcp: null
# web ui mapping
webui: "http://[HOST]:[PORT:3000]"
ingress: true
ingress_port: "3000"
ingress_stream: true