general = {
    name = "{{NAME}}";
    output_backend = "pipe";
};

pipe = {
    name = "/tmp/audio_fifo";
};

// enable metadata pipe
metadata = {
    enabled = "yes";
    include_cover_art = "yes";
    pipe_name = "/tmp/shairport_metadata";
};